# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [riskiseptiawan, riskiseptiawan890]
patreon: # Replace with a single Patreon username Riski Septiawan
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://www.instagram.com/riskiseptiawan890', 'https://www
tiktok.com/@riski__septiawan', 'https://www.patreon.com/Riskipay89/creators', 'https://twitter.com/Riskipay89']
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://www.facebook.com/riski.singamania.56', 'https://www.facebook.com/profile.php?id=100068618284370', 'https://www.facebook.com/Riskiseptiawann/']
